# syntax=docker/dockerfile:1.4

FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY sample.env .env

EXPOSE 8062

CMD ["python", "-m", "app.main"]


